### ISSUE TITLE
ToDo for initial text-only version

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/scrape-twitter-dm#1]
Tagline: output is e-pub

Readme:

- [x] Mention Python as dependency.
- [x] Show anonymised sample output of text file.
- [x] ...

Scrape_twitter_dm.ts:

- [x] Fix `to_name()` to return Id if name is not available.
- [x] Fix `to_id()` to return name if Id is not available.
- [x] Allow for participant to be specified both as 'name:id' and 'id' only.
- [x] Add option `-h`, `--help` to show usage.
- [x] Add option `-l`, `--list-conversations` to list conversations in archive, and remove it from normal processing.
- [x] Add option `-u`, `--list-user-info` to list information on the owner of the archive, and remove it from normal processing.
- [x] Move error messages from `require_*()` to `main()` and use
  - `if (count(participants) < 2) ...`
  - `if (!is_gpdr(archive)) ...`
- [x] ...

Scrape_twitter_dm.py:

- [x] Implement markdown to e-pub conversion using pandoc.
- [x] Allow to assign participant style for sender-name.
- [ ] ...

Other:

- [x] ...
